// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var deg, ledA, ledB, ledC, ledD, recDeg, recordKnob, volDeg, volumeKnob, wheel;
    deg = 0;
    wheel = $('.wheel');
    wheel.bind("mousewheel", function(e) {
      if (e.originalEvent.wheelDelta / 120 > 0) {
        deg += 15;
      } else {
        deg -= 15;
      }
      wheel.css("-moz-transform", "rotate(" + deg + "deg)");
      wheel.css("-webkit-transform", "rotate(" + deg + "deg)");
      wheel.css("-o-transform", "rotate(" + deg + "deg)");
      return wheel.css("-ms-transform", "rotate(" + deg + "deg)");
    });
    recDeg = 0;
    recordKnob = $('.record-knob');
    recordKnob.bind("mousewheel", function(e) {
      if (e.originalEvent.wheelDelta / 120 > 0) {
        recDeg += 10;
      } else {
        recDeg -= 10;
      }
      if (recDeg >= -150 && recDeg <= 150) {
        recordKnob.css("-moz-transform", "rotate(" + recDeg + "deg)");
        recordKnob.css("-webkit-transform", "rotate(" + recDeg + "deg)");
        recordKnob.css("-o-transform", "rotate(" + recDeg + "deg)");
        return recordKnob.css("-ms-transform", "rotate(" + recDeg + "deg)");
      }
    });
    volDeg = 0;
    volumeKnob = $('.volume-knob');
    volumeKnob.bind("mousewheel", function(e) {
      if (e.originalEvent.wheelDelta / 120 > 0) {
        volDeg += 10;
      } else {
        volDeg -= 10;
      }
      if (volDeg >= -150 && volDeg <= 150) {
        volumeKnob.css("-moz-transform", "rotate(" + volDeg + "deg)");
        volumeKnob.css("-webkit-transform", "rotate(" + volDeg + "deg)");
        volumeKnob.css("-o-transform", "rotate(" + volDeg + "deg)");
        return volumeKnob.css("-ms-transform", "rotate(" + volDeg + "deg)");
      }
    });
    ledA = $('#led-bank-a');
    ledB = $('#led-bank-b');
    ledC = $('#led-bank-c');
    ledD = $('#led-bank-d');
    $('#bank-a').click(function() {
      $('.bank-leds.active').removeClass('active');
      ledA.toggleClass('active');
      if (ledA.hasClass('active')) {
        return window.currentPadBank = "A";
      }
    });
    $('#bank-b').click(function() {
      $('.bank-leds.active').removeClass('active');
      ledB.toggleClass('active');
      if (ledB.hasClass('active')) {
        return window.currentPadBank = "B";
      }
    });
    $('#bank-c').click(function() {
      $('.bank-leds.active').removeClass('active');
      ledC.toggleClass('active');
      if (ledC.hasClass('active')) {
        return window.currentPadBank = "C";
      }
    });
    return $('#bank-d').click(function() {
      $('.bank-leds.active').removeClass('active');
      ledD.toggleClass('active');
      if (ledD.hasClass('active')) {
        return window.currentPadBank = "D";
      }
    });
  });

}).call(this);

/*
//@ sourceMappingURL=mpc.map
*/
